name: sandbox-aws-copilot-cli

services:
    aws-copilot-cli:
        build: .
        volumes:
            - .:/usr/src/app
        env_file: cli.env
        environment:
            AWS_DEFAULT_REGION: ap-northeast-1
        tty: true
        privileged: true
        command: /sbin/init
